sudo: false
language: python
matrix:
  include:
    - os: linux
      python: "2.7"
    - os: linux
      python: "3.3"
    - os: linux
      python: "3.4"
    - os: linux
      python: "3.5"
    - os: osx
      osx_image: xcode7
      language: generic
# Perform the manual steps on osx to install python3 and activate venv
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip3 install virtualenv; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv venv -p python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate; fi
install:
  - pip install -U pip
  - pip install -r requirements.txt
  - pip install azure-storage
  - pip install coveralls
  - pip uninstall -y azure-common
script: 
  - cd azure-servicebus/tests
  - bash run-servicebus
  - cd ../..
  - cd azure-servicemanagement-legacy/tests
  - bash run-legacy-mgmt
  - cd ../..
  - cd azure-mgmt/tests
  - bash run-mgmt
  - cd ../..
  - rm -f .coverage
  - coverage combine azure-mgmt/tests/.coverage azure-servicebus/tests/.coverage azure-servicemanagement-legacy/tests/.coverage
  - coverage report
after_success:
  coveralls
