parameters:
  - name: MgmtPackages
    type: object
    default:
      # azure-mgmt-connectedvmware:
      #   ServiceDirectory: connectedvmware
      #   Version: '1.0.0'
      # azure-mgmt-oep:
      #   ServiceDirectory: oep
      #   Version: '1.0.0b2'
      # azure-mgmt-devhub:
      #   ServiceDirectory: devhub
      #   Version: '1.0.0b1'
      # azure-mgmt-consumption:
      #   ServiceDirectory: consumption
      #   Version: '11.0.0b1'
      # azure-mgmt-managedapplications:
      #   ServiceDirectory: managedapplications
      #   Version: '1.0.0b1'
      # azure-mgmt-advisor:
      #   ServiceDirectory: advisor
      #   Version: '10.0.0b1'
      # azure-mgmt-operationsmanagement:
      #   ServiceDirectory: operationsmanagement
      #   Version: '2.0.0b1'
      # azure-mgmt-iothub:
      #   ServiceDirectory: iothub
      #   Version: '3.0.0'
      # azure-mgmt-iothubprovisioningservices:
      #   ServiceDirectory: iothub
      #   Version: '1.2.0b2'
      # azure-mgmt-iotcentral:
      #   ServiceDirectory: iothub
      #   Version: '10.0.0b2'
      # azure-mgmt-managedservices:
      #   ServiceDirectory: managedservices
      #   Version: '7.0.0b1'
      # azure-mgmt-signalr:
      #   ServiceDirectory: signalr
      #   Version: '2.0.0b2'
      # azure-mgmt-extendedlocation:
      #   ServiceDirectory: extendedlocation
      #   Version: '1.2.0b1'
      # azure-mgmt-automation:
      #   ServiceDirectory: automation
      #   Version: '1.1.0b3'
      # azure-mgmt-networkcloud:
      #   ServiceDirectory: networkcloud
      #   Version: '1.0.0'
      # azure-mgmt-appcomplianceautomation:
      #   ServiceDirectory: appcomplianceautomation
      #   Version: '1.0.0b1'
      # azure-mgmt-billing:
      #   ServiceDirectory: billing
      #   Version: '6.1.0b1'
      # azure-mgmt-media:
      #   ServiceDirectory: media
      #   Version: '10.2.0'
      # azure-mgmt-dnsresolver:
      #   ServiceDirectory: dnsresolver
      #   Version: '1.1.0b1'
      # azure-mgmt-storagecache:
      #   ServiceDirectory: storage
      #   Version: '1.6.0b1'
      # azure-mgmt-storage:
      #   ServiceDirectory: storage
      #   Version: '21.1.0'
      # azure-mgmt-storagesync:
      #   ServiceDirectory: storage
      #   Version: '2.0.0b1'
      # azure-mgmt-storageimportexport:
      #   ServiceDirectory: storage
      #   Version: '1.0.0b2'
      # azure-mgmt-timeseriesinsights:
      #   ServiceDirectory: timeseriesinsights
      #   Version: '2.0.0b1'
      # azure-mgmt-synapse:
      #   ServiceDirectory: synapse
      #   Version: '2.1.0b7'
      # azure-mgmt-resourceconnector:
      #   ServiceDirectory: resourceconnector
      #   Version: '1.0.0'
      # azure-mgmt-notificationhubs:
      #   ServiceDirectory: notificationhubs
      #   Version: '8.1.0b1'
      # azure-mgmt-streamanalytics:
      #   ServiceDirectory: streamanalytics
      #   Version: '2.0.0b2'
      # azure-mgmt-customproviders:
      #   ServiceDirectory: customproviders
      #   Version: '1.1.0b1'
      # azure-mgmt-containerregistry:
      #   ServiceDirectory: containerregistry
      #   Version: '10.3.0'
      # azure-mgmt-web:
      #   ServiceDirectory: appservice
      #   Version: '7.2.0'
      # azure-mgmt-monitor:
      #   ServiceDirectory: monitor
      #   Version: '6.0.2'
      # azure-mgmt-managednetworkfabric:
      #   ServiceDirectory: managednetworkfabric
      #   Version: '1.0.0'
      # azure-mgmt-appplatform:
      #   ServiceDirectory: appplatform
      #   Version: '9.0.0'
      # azure-mgmt-msi:
      #   ServiceDirectory: resources
      #   Version: '7.1.0b1'
      # azure-mgmt-resource:
      #   ServiceDirectory: resources
      #   Version: '23.1.0b2'
      # azure-mgmt-resourcegraph:
      #   ServiceDirectory: resources
      #   Version: '8.1.0b3'
      # azure-mgmt-databox:
      #   ServiceDirectory: databox
      #   Version: '2.0.0'
      # azure-mgmt-maps:
      #   ServiceDirectory: maps
      #   Version: '2.1.0'
      # azure-mgmt-education:
      #   ServiceDirectory: education
      #   Version: '1.0.0b2'
      # azure-mgmt-costmanagement:
      #   ServiceDirectory: costmanagement
      #   Version: '4.0.1'
      # azure-mgmt-workloadmonitor:
      #   ServiceDirectory: workloadmonitor
      #   Version: '1.0.0b4'
      # azure-mgmt-cognitiveservices:
      #   ServiceDirectory: cognitiveservices
      #   Version: '13.5.0'
      # azure-mgmt-workloads:
      #   ServiceDirectory: workloads
      #   Version: '1.0.0'
      # azure-mgmt-datadog:
      #   ServiceDirectory: datadog
      #   Version: '2.1.0'
      # azure-mgmt-resourcemover:
      #   ServiceDirectory: resourcemover
      #   Version: '1.1.0'
      # azure-mgmt-paloaltonetworksngfw:
      #   ServiceDirectory: paloaltonetworks
      #   Version: '2.0.0b1'
      # azure-mgmt-recoveryservicessiterecovery:
      #   ServiceDirectory: recoveryservices
      #   Version: '1.2.0'
      # azure-mgmt-recoveryservices:
      #   ServiceDirectory: recoveryservices
      #   Version: '2.5.0'
      # azure-mgmt-recoveryservicesbackup:
      #   ServiceDirectory: recoveryservices
      #   Version: '9.0.0'
      # azure-mgmt-vmwarecloudsimple:
      #   ServiceDirectory: compute
      #   Version: '1.0.0b2'
      # azure-mgmt-avs:
      #   ServiceDirectory: compute
      #   Version: '8.0.0'
      # azure-mgmt-imagebuilder:
      #   ServiceDirectory: compute
      #   Version: '1.3.0'
      # azure-mgmt-portal:
      #   ServiceDirectory: portal
      #   Version: '1.1.0b1'
      # azure-mgmt-logic:
      #   ServiceDirectory: logic
      #   Version: '10.1.0b1'
      azure-mgmt-graphservices:
        ServiceDirectory: graphservices
        Version: '1.0.0'
      azure-mgmt-deploymentmanager:
        ServiceDirectory: deploymentmanager
        Version: '2.0.0b1'
      azure-mgmt-azurearcdata:
        ServiceDirectory: azurearcdata
        Version: '2.0.0b1'
      azure-mgmt-selfhelp:
        ServiceDirectory: selfhelp
        Version: '2.0.0b2'
      azure-mgmt-baremetalinfrastructure:
        ServiceDirectory: baremetalinfrastructure
        Version: '1.1.0b2'
      azure-mgmt-redhatopenshift:
        ServiceDirectory: redhatopenshift
        Version: '1.4.0'
      azure-mgmt-cdn:
        ServiceDirectory: cdn
        Version: '13.0.0'
      azure-mgmt-datalake-store:
        ServiceDirectory: datalake
        Version: '1.1.0b1'
      azure-mgmt-datalake-analytics:
        ServiceDirectory: datalake
        Version: '1.0.0b2'
      azure-mgmt-quantum:
        ServiceDirectory: quantum
        Version: '1.0.0b4'
      azure-mgmt-astro:
        ServiceDirectory: astro
        Version: '1.0.0b1'
      azure-mgmt-sphere:
        ServiceDirectory: sphere
        Version: '1.0.0b1'
      azure-mgmt-datalake-nspkg:
        ServiceDirectory: nspkg
        Version: '3.0.1'
      azure-mgmt-nspkg:
        ServiceDirectory: nspkg
        Version: '3.0.2'
      azure-mgmt-keyvault:
        ServiceDirectory: keyvault
        Version: '10.3.0'
      azure-mgmt-azurestackhci:
        ServiceDirectory: azurestackhci
        Version: '8.0.0b3'
      azure-mgmt-hybridconnectivity:
        ServiceDirectory: hybridconnectivity
        Version: '1.0.0'
      azure-mgmt-managementpartner:
        ServiceDirectory: managementpartner
        Version: '1.1.0b1'
      azure-mgmt-serialconsole:
        ServiceDirectory: serialconsole
        Version: '1.1.0b1'
      azure-mgmt-security:
        ServiceDirectory: security
        Version: '6.0.0'
      azure-mgmt-dashboard:
        ServiceDirectory: dashboard
        Version: '1.1.0'
      azure-mgmt-kusto:
        ServiceDirectory: kusto
        Version: '3.3.0'
      azure-mgmt-hybridkubernetes:
        ServiceDirectory: hybridkubernetes
        Version: '1.2.0b1'
      azure-mgmt-servicefabricmanagedclusters:
        ServiceDirectory: servicefabricmanagedclusters
        Version: '2.0.0b6'
      azure-mgmt-commerce:
        ServiceDirectory: commerce
        Version: '6.1.0b1'
      azure-mgmt-orbital:
        ServiceDirectory: orbital
        Version: '2.0.0'
      azure-mgmt-servicelinker:
        ServiceDirectory: servicelinker
        Version: '1.2.0b1'
      azure-mgmt-servicenetworking:
        ServiceDirectory: servicenetworking
        Version: '1.0.0'
      azure-mgmt-servicefabric:
        ServiceDirectory: servicefabric
        Version: '2.2.0b1'
      azure-mgmt-elastic:
        ServiceDirectory: elastic
        Version: '1.1.0b3'
      azure-mgmt-securitydevops:
        ServiceDirectory: securitydevops
        Version: '1.0.0b2'
      azure-mgmt:
        ServiceDirectory: core
        Version: '5.0.0'
      azure-mgmt-core:
        ServiceDirectory: core
        Version: '1.4.0'
      azure-mgmt-alertsmanagement:
        ServiceDirectory: alertsmanagement
        Version: '2.0.0b2'
      azure-mgmt-support:
        ServiceDirectory: support
        Version: '6.1.0b2'
      azure-mgmt-containerinstance:
        ServiceDirectory: containerinstance
        Version: '10.1.0'
      azure-mgmt-hdinsight:
        ServiceDirectory: hdinsight
        Version: '9.0.0'
      azure-mgmt-hdinsightcontainers:
        ServiceDirectory: hdinsight
        Version: '1.0.0b1'
      azure-mgmt-marketplaceordering:
        ServiceDirectory: marketplaceordering
        Version: '1.2.0b1'
      azure-mgmt-deviceupdate:
        ServiceDirectory: deviceupdate
        Version: '1.1.0'
      azure-mgmt-reservations:
        ServiceDirectory: reservations
        Version: '2.3.0'
      azure-mgmt-apimanagement:
        ServiceDirectory: apimanagement
        Version: '4.0.0'
      azure-mgmt-containerservice:
        ServiceDirectory: containerservice
        Version: '29.1.0'
      azure-mgmt-containerservicefleet:
        ServiceDirectory: containerservice
        Version: '1.0.0'
      azure-mgmt-defendereasm:
        ServiceDirectory: defendereasm
        Version: '1.0.0b1'
      azure-mgmt-loganalytics:
        ServiceDirectory: loganalytics
        Version: '13.0.0b6'
      azure-mgmt-authorization:
        ServiceDirectory: authorization
        Version: '4.0.0'
      azure-mgmt-servicebus:
        ServiceDirectory: servicebus
        Version: '8.2.0'
      azure-mgmt-iotfirmwaredefense:
        ServiceDirectory: iotfirmwaredefense
        Version: '1.0.0b1'
      azure-mgmt-peering:
        ServiceDirectory: peering
        Version: '2.0.0b1'
      azure-mgmt-redis:
        ServiceDirectory: redis
        Version: '14.3.0'
      azure-mgmt-hanaonazure:
        ServiceDirectory: hanaonazure
        Version: '1.1.0b1'
      azure-mgmt-quota:
        ServiceDirectory: quota
        Version: '1.1.0'
      azure-mgmt-webpubsub:
        ServiceDirectory: webpubsub
        Version: '2.0.0b2'
      azure-mgmt-databricks:
        ServiceDirectory: databricks
        Version: '2.0.0'
      azure-mgmt-appconfiguration:
        ServiceDirectory: appconfiguration
        Version: '3.0.0'
      azure-mgmt-hybridcompute:
        ServiceDirectory: hybridcompute
        Version: '9.0.0b1'
      azure-mgmt-managementgroups:
        ServiceDirectory: managementgroups
        Version: '1.1.0b1'
      azure-mgmt-edgeorder:
        ServiceDirectory: edgeorder
        Version: '2.0.0b1'
      azure-mgmt-networkanalytics:
        ServiceDirectory: networkanalytics
        Version: '1.0.0'
      azure-mgmt-qumulo:
        ServiceDirectory: qumulo
        Version: '1.0.0'
      azure-mgmt-dns:
        ServiceDirectory: network
        Version: '8.1.0'
      azure-mgmt-network:
        ServiceDirectory: network
        Version: '25.3.0'
      azure-mgmt-privatedns:
        ServiceDirectory: network
        Version: '1.1.0'
      azure-mgmt-frontdoor:
        ServiceDirectory: network
        Version: '1.1.0'
      azure-mgmt-digitaltwins:
        ServiceDirectory: digitaltwins
        Version: '6.4.0'
      azure-mgmt-hybridnetwork:
        ServiceDirectory: hybridnetwork
        Version: '2.0.0'
      azure-mgmt-playwrighttesting:
        ServiceDirectory: playwrighttesting
        Version: '1.0.0b2'
      azure-mgmt-azurelargeinstance:
        ServiceDirectory: azurelargeinstance
        Version: '1.0.0b1'
      azure-mgmt-datamigration:
        ServiceDirectory: datamigration
        Version: '10.1.0b1'
      azure-mgmt-voiceservices:
        ServiceDirectory: voiceservices
        Version: '1.0.0'
      azure-mgmt-policyinsights:
        ServiceDirectory: policyinsights
        Version: '1.1.0b4'
      azure-mgmt-storagemover:
        ServiceDirectory: storagemover
        Version: '2.0.0'
      azure-mgmt-subscription:
        ServiceDirectory: subscription
        Version: '3.2.0b1'
      azure-mgmt-hybridcontainerservice:
        ServiceDirectory: hybridcontainerservice
        Version: '1.0.0'
      azure-mgmt-kubernetesconfiguration:
        ServiceDirectory: kubernetesconfiguration
        Version: '3.1.0'
      azure-mgmt-recoveryservicesdatareplication:
        ServiceDirectory: recoveryservicesdatareplication
        Version: '1.0.0b1'
      azure-mgmt-devspaces:
        ServiceDirectory: aks
        Version: '1.0.0b3'
      azure-mgmt-storagepool:
        ServiceDirectory: storagepool
        Version: '1.1.0b1'
      azure-mgmt-securityinsight:
        ServiceDirectory: securityinsight
        Version: '2.0.0b2'
      azure-mgmt-cosmosdb:
        ServiceDirectory: cosmos
        Version: '10.0.0b2'
      azure-mgmt-attestation:
        ServiceDirectory: attestation
        Version: '2.0.0b1'
      azure-mgmt-healthbot:
        ServiceDirectory: healthbot
        Version: '1.0.0b2'
      azure-mgmt-resourcehealth:
        ServiceDirectory: resourcehealth
        Version: '1.0.0b5'
      azure-mgmt-dynatrace:
        ServiceDirectory: dynatrace
        Version: '2.0.0'
      azure-mgmt-guestconfig:
        ServiceDirectory: machinelearning
        Version: '1.0.0b2'
      azure-mgmt-machinelearningservices:
        ServiceDirectory: machinelearning
        Version: '2.0.0b2'
      azure-mgmt-machinelearningcompute:
        ServiceDirectory: machinelearning
        Version: '1.0.0b2'
      azure-mgmt-agrifood:
        ServiceDirectory: agrifood
        Version: '1.0.0b3'
      azure-mgmt-dataprotection:
        ServiceDirectory: dataprotection
        Version: '1.3.0'
      azure-mgmt-labservices:
        ServiceDirectory: labservices
        Version: '2.1.0b1'
      azure-mgmt-testbase:
        ServiceDirectory: testbase
        Version: '1.0.0b2'
      azure-mgmt-chaos:
        ServiceDirectory: chaos
        Version: '1.1.0'
      azure-mgmt-confidentialledger:
        ServiceDirectory: confidentialledger
        Version: '2.0.0b3'
      azure-mgmt-databoxedge:
        ServiceDirectory: databoxedge
        Version: '2.0.0b1'
      azure-mgmt-loadtesting:
        ServiceDirectory: loadtesting
        Version: '1.0.0'
      azure-mgmt-mixedreality:
        ServiceDirectory: mixedreality
        Version: '1.1.0b1'
      azure-mgmt-eventhub:
        ServiceDirectory: eventhub
        Version: '11.0.0'
      azure-mgmt-scvmm:
        ServiceDirectory: scvmm
        Version: '1.0.0b2'
      azure-mgmt-devcenter:
        ServiceDirectory: devcenter
        Version: '1.1.0b1'
      azure-mgmt-rdbms:
        ServiceDirectory: rdbms
        Version: '10.2.0b15'
      azure-mgmt-app:
        ServiceDirectory: app
        Version: '1.0.0b2'
      azure-mgmt-netapp:
        ServiceDirectory: netapp
        Version: '12.0.0b1'
      azure-mgmt-elasticsan:
        ServiceDirectory: elasticsan
        Version: '1.0.0'
      azure-mgmt-relay:
        ServiceDirectory: relay
        Version: '2.0.0b1'
      azure-mgmt-datashare:
        ServiceDirectory: datashare
        Version: '1.1.0b1'
      azure-mgmt-devtestlabs:
        ServiceDirectory: devtestlabs
        Version: '10.0.0b1'
      azure-mgmt-billingbenefits:
        ServiceDirectory: billingbenefits
        Version: '1.0.0b1'
      azure-mgmt-purview:
        ServiceDirectory: purview
        Version: '1.1.0b1'
      azure-mgmt-applicationinsights:
        ServiceDirectory: applicationinsights
        Version: '4.0.0'
      azure-mgmt-logz:
        ServiceDirectory: logz
        Version: '1.1.0b1'
      azure-mgmt-eventgrid:
        ServiceDirectory: eventgrid
        Version: '10.3.0b3'
      azure-mgmt-healthcareapis:
        ServiceDirectory: healthcareapis
        Version: '2.0.0'
      azure-mgmt-trafficmanager:
        ServiceDirectory: trafficmanager
        Version: '1.1.0'
      azure-mgmt-videoanalyzer:
        ServiceDirectory: videoanalyzer
        Version: '1.0.0b4'
      azure-mgmt-redisenterprise:
        ServiceDirectory: redisenterprise
        Version: '3.0.0'
      azure-mgmt-desktopvirtualization:
        ServiceDirectory: desktopvirtualization
        Version: '1.1.0'
      azure-mgmt-apicenter:
        ServiceDirectory: apicenter
        Version: '1.0.0'
      azure-mgmt-automanage:
        ServiceDirectory: automanage
        Version: '2.0.0b1'
      azure-mgmt-maintenance:
        ServiceDirectory: maintenance
        Version: '2.2.0b1'
      azure-mgmt-fluidrelay:
        ServiceDirectory: fluidrelay
        Version: '1.1.0b1'
      azure-mgmt-hardwaresecuritymodules:
        ServiceDirectory: hardwaresecuritymodules
        Version: '1.0.0b1'
      azure-mgmt-springappdiscovery:
        ServiceDirectory: springappdiscovery
        Version: '1.0.0b1'
      azure-mgmt-botservice:
        ServiceDirectory: botservice
        Version: '2.0.0'
      azure-mgmt-sql:
        ServiceDirectory: sql
        Version: '4.0.0b15'
      azure-mgmt-sqlvirtualmachine:
        ServiceDirectory: sql
        Version: '1.0.0b6'
      azure-mgmt-networkfunction:
        ServiceDirectory: networkfunction
        Version: '1.0.0b1'
      azure-mgmt-powerbidedicated:
        ServiceDirectory: powerbidedicated
        Version: '1.1.0b1'
      azure-mgmt-azurestack:
        ServiceDirectory: azurestack
        Version: '2.0.0b1'

jobs:
  - job: 'PublishAllMgmtDocs'
    timeoutInMinutes: 240
    steps:
      - task: UsePythonVersion@0
        displayName: 'Use Python 3.11'
        inputs:
          versionSpec: '3.11'
    
      - script: |
          python -m pip install setuptools==58.3.0
          python -m pip install -r eng/ci_tools.txt
        displayName: 'Prep Environment'
      - ${{ each pkg in parameters.MgmtPackages }}:
        - task: PythonScript@0
          displayName: 'checkout library tag'
          inputs:
            scriptPath: 'doc/sphinx/temp_mgmt/checkout_tag.py'
            arguments: >-
              --package=${{ pkg.key }}
              --service=${{ pkg.value.ServiceDirectory }}
              --version=${{ pkg.value.Version }}
        - task: PythonScript@0
          displayName: 'Generate Docs'
          inputs:
            scriptPath: 'scripts/devops_tasks/dispatch_tox.py'
            arguments: >-
              ${{ pkg.key }}
              --service=${{ pkg.value.ServiceDirectory }}
              --toxenv=sphinx
      - template: /eng/common/pipelines/templates/steps/publish-artifact.yml
        parameters:
          ArtifactPath: '$(Build.SourcesDirectory)/_docs'
          ArtifactName: 'documentation'
