trigger: none

extends:
    template: ../../eng/pipelines/templates/stages/archetype-sdk-tests.yml
    parameters:
      BuildTargetingString: azure-ai-textanalytics
      ServiceDirectory: textanalytics
      UseFederatedAuth: true
      CloudConfig:
        Public:
          Location: eastus
          ServiceConnection: azure-sdk-tests
          SubscriptionConfigurationFilePath: eng/common/TestResources/sub-config/AzurePublicMsft.json
          SubscriptionConfigurations:
            - $(sub-config-azure-cloud-test-resources)
            - $(sub-config-text-analytics-azure-cloud-test-resources)
          MatrixReplace:
            - TestSamples=.*/true
        UsGov:
          SubscriptionConfiguration: $(sub-config-gov-test-resources)
        China:
          SubscriptionConfiguration: $(sub-config-cn-test-resources)
      SupportedClouds: 'Public,UsGov,China'
      EnvVars:
        AZURE_SUBSCRIPTION_ID: $(TEXTANALYTICS_SUBSCRIPTION_ID)
        TEST_MODE: 'RunLiveNoRecord'
        AZURE_SKIP_LIVE_RECORDING: 'True'
        AZURE_TEST_RUN_LIVE: 'true'
