trigger:
  branches:
    exclude:
    - pipelinev3-v2

pr:
  branches:
    include:
    - pipelinev3*

parameters:
  - name: Service
    type: string
    default: auto

extends:
  template: ../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: ${{ parameters.Service }}
    BuildTargetingString: "*"
    ValidateFormatting: true
    TestProxy: true